# Generated by Django 5.0.3 on 2024-03-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_source_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
